### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by troler36** [borodust/aw-sdl#1]
This is not a bug request, I just wanted to say thank you! I've never thought that there was a CL wrapper for SDL. But I wanted one to exist. And you've made this reality. Thank you, thank you. You're amazing, keep up the work.
![image](https://user-images.githubusercontent.com/39880578/158053136-d07dd696-0fb1-40f3-a443-7d6ebafd3c36.png)

**Comment by borodust** [comment]
Thank you very much!

Just in case, CL has a couple more wrappers available: 
* https://github.com/lispgames/cl-sdl2
* https://github.com/Zulu-Inuoe/raw-bindings-sdl2

`cl-sdl2` is bit more high-level and verbose, but also oldest. `raw-bindings-sdl2` is low-level hand-tuned ones. `aw-sdl` is low-level fully auto-generated from headers.

If you have Lisp-related gamedev questions, feel free to join us in IRC channel [#lispgames](https://web.libera.chat/?channel=#lispgames) at [irc.libera.chat:6697](ircs://irc.libera.chat:6697) or [Lisp Discord server](https://discord.gg/hhk46CE) in `#lisp-gamedev` channel.
